name: dependency check
on: [push, pull_request]

jobs:
  python:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install poetry
        run: python3 -m pip install poetry

      - name: poetry --help
        run: poetry --help

      - name: poetry install
        run: poetry install
